services:
  satellite-pass-calculator:
    build: .
    ports:
      - "1309:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./static:/app/static
    restart: unless-stopped