[tool.poetry]
name = "szwecja-gs"
version = "0.1.0"
description = ""
authors = ["Patryk Niczke <p.niczke@satrev.space>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.5"
pandas = "^2.2.3"
skyfield = "^1.53"
matplotlib = "^3.10.1"
requests = "^2.32.3"
openpyxl = "^3.1.5"
flask = "^3.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
